export const allItems = [
  { id: "100", name: "Automative" },
  { id: "101", name: "Baby" },
  { id: "103", name: "Baeuty & Personal Care" },
  { id: "104", name: "Books" },
  { id: "105", name: "Boy's Fashion" },
  { id: "106", name: "Computer" },
  { id: "107", name: "Deals" },
  { id: "108", name: "Digital Music" },
  { id: "109", name: "Electronics" },
  { id: "110", name: "Girl's Fashion" },
  { id: "111", name: "Health & Household" },
  { id: "112", name: "Home & Kitchen" },
  { id: "113", name: "Home & Kitchen" },
  { id: "114", name: "Industrial & Scientific" },
  { id: "115", name: "Kiddie Store" },
  { id: "116", name: "Luggage" },
  { id: "117", name: "Men's Fashion" },
  { id: "118", name: "Movies & TV" },
  { id: "119", name: "Music, CDs & Vinyl" },
  { id: "120", name: "Pet Supplies" },
  { id: "121", name: "Prime Video" },
  { id: "122", name: "Software" },
  { id: "123", name: "Sport & Outdoors" },
  { id: "124", name: "Tools & Home Appilication" },
  { id: "125", name: "Toys & Games" },
  { id: "126", name: "Video Games" },
  { id: "127", name: "Women's Fashion" },
];

export const headerItems = [
  // {id: 1, title: "All", headIcon: <Menu />},
  { id: 2, title: "Today's Deals" },
  { id: 3, title: "Customer Service" },
  { id: 4, title: "Gift Cards" },
  { id: 5, title: "Registry" },
  { id: 6, title: "Sell" },
];
